version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    post_checkout:
      - git submodule update --init

sphinx:
  builder: dirhtml
  configuration: conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
