version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git submodule update --init

sphinx:
  builder: dirhtml
  configuration: conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
