# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py39"
line-length = 120
extend-exclude=[
    ".git,",
    "__pycache__",
    "build",
    "tools/**",
]
lint.select = [
    "ALL",
]
lint.extend-ignore = [
    "ANN", # Ignore missing annotations
    "COM812", # May cause conflicts when used with the formatter
    "D", # Ignore docstrings
    "E501", # Line too long
    "E741", # Ambiguous variable name
    "ISC001",  # May cause conflicts when used with the formatter
    "PD011", # Use `.to_numpy()` instead of `.values`
    "T201", # Print statements
]

[lint.per-file-ignores]
"exts/rawfiles.py" = [
    "INP001", # Part of an implicit namespace package
]
"posts/2024/eclipse_helpers.py" = [
    "INP001", # Part of an implicit namespace package
]
"docs/conf.py" = [
    "INP001", # Part of an implicit namespace package
]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"
